# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'ServiceModel.Configuration.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/t:restore;build'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- script: dotnet pack # define version variable elsewhere in your pipeline
- task: CopyFiles@2
  inputs:
    #sourceFolder: # Optional
    contents: '**/*nupkg' 
    targetFolder: '$(build.artifactstagingdirectory)'
    #cleanTargetFolder: false # Optional
    #overWrite: false # Optional
    flattenFolders: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'

#- task: NuGetCommand@2
#  inputs:
#    command: push
#    nuGetFeedType: external
#    publishFeedCredentials: '<Name of the NuGet service connection>'
#    versioningScheme: byEnvVar
#    versionEnvVar: version
