//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceModel.Configuration.ConfigurationManager.Helpers.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigBindingExtensionNotFound.
        /// </summary>
        internal static string ConfigBindingExtensionNotFound {
            get {
                return ResourceManager.GetString("ConfigBindingExtensionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigDuplicateExtensionName.
        /// </summary>
        internal static string ConfigDuplicateExtensionName {
            get {
                return ResourceManager.GetString("ConfigDuplicateExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigDuplicateExtensionType.
        /// </summary>
        internal static string ConfigDuplicateExtensionType {
            get {
                return ResourceManager.GetString("ConfigDuplicateExtensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigDuplicateItem.
        /// </summary>
        internal static string ConfigDuplicateItem {
            get {
                return ResourceManager.GetString("ConfigDuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigDuplicateKey.
        /// </summary>
        internal static string ConfigDuplicateKey {
            get {
                return ResourceManager.GetString("ConfigDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigDuplicateKeyAtSameScope.
        /// </summary>
        internal static string ConfigDuplicateKeyAtSameScope {
            get {
                return ResourceManager.GetString("ConfigDuplicateKeyAtSameScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigElementKeyNull.
        /// </summary>
        internal static string ConfigElementKeyNull {
            get {
                return ResourceManager.GetString("ConfigElementKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigElementKeysNull.
        /// </summary>
        internal static string ConfigElementKeysNull {
            get {
                return ResourceManager.GetString("ConfigElementKeysNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigElementTypeNotAllowed.
        /// </summary>
        internal static string ConfigElementTypeNotAllowed {
            get {
                return ResourceManager.GetString("ConfigElementTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigEndpointExtensionNotFound.
        /// </summary>
        internal static string ConfigEndpointExtensionNotFound {
            get {
                return ResourceManager.GetString("ConfigEndpointExtensionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigExtensionCollectionNotFound.
        /// </summary>
        internal static string ConfigExtensionCollectionNotFound {
            get {
                return ResourceManager.GetString("ConfigExtensionCollectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigExtensionTypeNotRegisteredInCollection.
        /// </summary>
        internal static string ConfigExtensionTypeNotRegisteredInCollection {
            get {
                return ResourceManager.GetString("ConfigExtensionTypeNotRegisteredInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidAttribute.
        /// </summary>
        internal static string ConfigInvalidAttribute {
            get {
                return ResourceManager.GetString("ConfigInvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidBindingName.
        /// </summary>
        internal static string ConfigInvalidBindingName {
            get {
                return ResourceManager.GetString("ConfigInvalidBindingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidCertificateValidatorType.
        /// </summary>
        internal static string ConfigInvalidCertificateValidatorType {
            get {
                return ResourceManager.GetString("ConfigInvalidCertificateValidatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidClassFactoryValue.
        /// </summary>
        internal static string ConfigInvalidClassFactoryValue {
            get {
                return ResourceManager.GetString("ConfigInvalidClassFactoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidClassInstanceValue.
        /// </summary>
        internal static string ConfigInvalidClassInstanceValue {
            get {
                return ResourceManager.GetString("ConfigInvalidClassInstanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidClientCredentialsType.
        /// </summary>
        internal static string ConfigInvalidClientCredentialsType {
            get {
                return ResourceManager.GetString("ConfigInvalidClientCredentialsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidCommonEndpointBehaviorType.
        /// </summary>
        internal static string ConfigInvalidCommonEndpointBehaviorType {
            get {
                return ResourceManager.GetString("ConfigInvalidCommonEndpointBehaviorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidEncodingValue.
        /// </summary>
        internal static string ConfigInvalidEncodingValue {
            get {
                return ResourceManager.GetString("ConfigInvalidEncodingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidEndpointBehavior.
        /// </summary>
        internal static string ConfigInvalidEndpointBehavior {
            get {
                return ResourceManager.GetString("ConfigInvalidEndpointBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidEndpointBehaviorType.
        /// </summary>
        internal static string ConfigInvalidEndpointBehaviorType {
            get {
                return ResourceManager.GetString("ConfigInvalidEndpointBehaviorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidEndpointName.
        /// </summary>
        internal static string ConfigInvalidEndpointName {
            get {
                return ResourceManager.GetString("ConfigInvalidEndpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidExtensionElement.
        /// </summary>
        internal static string ConfigInvalidExtensionElement {
            get {
                return ResourceManager.GetString("ConfigInvalidExtensionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidExtensionElementName.
        /// </summary>
        internal static string ConfigInvalidExtensionElementName {
            get {
                return ResourceManager.GetString("ConfigInvalidExtensionElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidExtensionType.
        /// </summary>
        internal static string ConfigInvalidExtensionType {
            get {
                return ResourceManager.GetString("ConfigInvalidExtensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidSection.
        /// </summary>
        internal static string ConfigInvalidSection {
            get {
                return ResourceManager.GetString("ConfigInvalidSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidServiceBehavior.
        /// </summary>
        internal static string ConfigInvalidServiceBehavior {
            get {
                return ResourceManager.GetString("ConfigInvalidServiceBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidStartValue.
        /// </summary>
        internal static string ConfigInvalidStartValue {
            get {
                return ResourceManager.GetString("ConfigInvalidStartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidType.
        /// </summary>
        internal static string ConfigInvalidType {
            get {
                return ResourceManager.GetString("ConfigInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidTypeForBinding.
        /// </summary>
        internal static string ConfigInvalidTypeForBinding {
            get {
                return ResourceManager.GetString("ConfigInvalidTypeForBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidTypeForBindingElement.
        /// </summary>
        internal static string ConfigInvalidTypeForBindingElement {
            get {
                return ResourceManager.GetString("ConfigInvalidTypeForBindingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInvalidTypeForEndpoint.
        /// </summary>
        internal static string ConfigInvalidTypeForEndpoint {
            get {
                return ResourceManager.GetString("ConfigInvalidTypeForEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigKeyNotFoundInElementCollection.
        /// </summary>
        internal static string ConfigKeyNotFoundInElementCollection {
            get {
                return ResourceManager.GetString("ConfigKeyNotFoundInElementCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigKeysDoNotMatch.
        /// </summary>
        internal static string ConfigKeysDoNotMatch {
            get {
                return ResourceManager.GetString("ConfigKeysDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigMessageEncodingAlreadyInBinding.
        /// </summary>
        internal static string ConfigMessageEncodingAlreadyInBinding {
            get {
                return ResourceManager.GetString("ConfigMessageEncodingAlreadyInBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigNoExtensionCollectionAssociatedWithType.
        /// </summary>
        internal static string ConfigNoExtensionCollectionAssociatedWithType {
            get {
                return ResourceManager.GetString("ConfigNoExtensionCollectionAssociatedWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigReadOnly.
        /// </summary>
        internal static string ConfigReadOnly {
            get {
                return ResourceManager.GetString("ConfigReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigSectionNotFound.
        /// </summary>
        internal static string ConfigSectionNotFound {
            get {
                return ResourceManager.GetString("ConfigSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigStreamUpgradeElementAlreadyInBinding.
        /// </summary>
        internal static string ConfigStreamUpgradeElementAlreadyInBinding {
            get {
                return ResourceManager.GetString("ConfigStreamUpgradeElementAlreadyInBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigTransportAlreadyInBinding.
        /// </summary>
        internal static string ConfigTransportAlreadyInBinding {
            get {
                return ResourceManager.GetString("ConfigTransportAlreadyInBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurationSchemaContainsX509IssuerSerialReference.
        /// </summary>
        internal static string ConfigurationSchemaContainsX509IssuerSerialReference {
            get {
                return ResourceManager.GetString("ConfigurationSchemaContainsX509IssuerSerialReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurationSchemaInsuffientForSecurityBindingElementInstance.
        /// </summary>
        internal static string ConfigurationSchemaInsuffientForSecurityBindingElementInstance {
            get {
                return ResourceManager.GetString("ConfigurationSchemaInsuffientForSecurityBindingElementInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlagEnumTypeExpected.
        /// </summary>
        internal static string FlagEnumTypeExpected {
            get {
                return ResourceManager.GetString("FlagEnumTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenericCallbackException.
        /// </summary>
        internal static string GenericCallbackException {
            get {
                return ResourceManager.GetString("GenericCallbackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting_MemoryGatesCheckFailedUnderPartialTrust.
        /// </summary>
        internal static string Hosting_MemoryGatesCheckFailedUnderPartialTrust {
            get {
                return ResourceManager.GetString("Hosting_MemoryGatesCheckFailedUnderPartialTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting_NoAbsoluteRelativeAddress.
        /// </summary>
        internal static string Hosting_NoAbsoluteRelativeAddress {
            get {
                return ResourceManager.GetString("Hosting_NoAbsoluteRelativeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting_RelativeAddressFormatError.
        /// </summary>
        internal static string Hosting_RelativeAddressFormatError {
            get {
                return ResourceManager.GetString("Hosting_RelativeAddressFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpMessageHandlerFactoryConfigInvalid_WithBothTypeAndHandlerList.
        /// </summary>
        internal static string HttpMessageHandlerFactoryConfigInvalid_WithBothTypeAndHandlerList {
            get {
                return ResourceManager.GetString("HttpMessageHandlerFactoryConfigInvalid_WithBothTypeAndHandlerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID0003.
        /// </summary>
        internal static string ID0003 {
            get {
                return ResourceManager.GetString("ID0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID0005.
        /// </summary>
        internal static string ID0005 {
            get {
                return ResourceManager.GetString("ID0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID0006.
        /// </summary>
        internal static string ID0006 {
            get {
                return ResourceManager.GetString("ID0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID1024.
        /// </summary>
        internal static string ID1024 {
            get {
                return ResourceManager.GetString("ID1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputMustBeDelegatingHandlerElementError.
        /// </summary>
        internal static string InputMustBeDelegatingHandlerElementError {
            get {
                return ResourceManager.GetString("InputMustBeDelegatingHandlerElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidFlagEnumType.
        /// </summary>
        internal static string InvalidFlagEnumType {
            get {
                return ResourceManager.GetString("InvalidFlagEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredAttributeMissing.
        /// </summary>
        internal static string RequiredAttributeMissing {
            get {
                return ResourceManager.GetString("RequiredAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureConversationBootstrapCannotUseSecureConversation.
        /// </summary>
        internal static string SecureConversationBootstrapCannotUseSecureConversation {
            get {
                return ResourceManager.GetString("SecureConversationBootstrapCannotUseSecureConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureConversationNeedsBootstrapSecurity.
        /// </summary>
        internal static string SecureConversationNeedsBootstrapSecurity {
            get {
                return ResourceManager.GetString("SecureConversationNeedsBootstrapSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionValueInvalid.
        /// </summary>
        internal static string SessionValueInvalid {
            get {
                return ResourceManager.GetString("SessionValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamUpgradeBindingElement.
        /// </summary>
        internal static string StreamUpgradeBindingElement {
            get {
                return ResourceManager.GetString("StreamUpgradeBindingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringNullOrEmpty.
        /// </summary>
        internal static string StringNullOrEmpty {
            get {
                return ResourceManager.GetString("StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueMustBePositive.
        /// </summary>
        internal static string ValueMustBePositive {
            get {
                return ResourceManager.GetString("ValueMustBePositive", resourceCulture);
            }
        }
    }
}
